name: "Create and Upload Leagu Cup Data"

on:
  schedule:
    # every wednesday at 18 from september to december
    - cron: "0 18 * 9-12 3"
  workflow_dispatch:

jobs:
  handle_war_data:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-22.04, r: "4.4" }
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      CI_COMMIT_MESSAGE: Added league Cup Data via Pipeline
      CI_COMMIT_AUTHOR: Github Action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup-r
      - name: Data handling
        run: Rscript -e "source('R/league-cup/league-cup.R', echo = TRUE)"
      - name: Add new files to git
        run: |
          git add nfl-schedule-*.json
          git add league-cup-*.json
      - name: Git Commit and Push
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "action@github.com"
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
